// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreVisitTracker.Infrastructure.Db;

#nullable disable

namespace StoreVisitTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250404121236_AddVisitStatus")]
    partial class AddVisitStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StoreVisitTracker.Domain.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Base64Image")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("VisitId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("StoreVisitTracker.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Groceries",
                            CreatedAt = new DateTime(2025, 4, 4, 12, 12, 36, 228, DateTimeKind.Utc).AddTicks(2421),
                            Name = "Chocolate"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 4, 4, 12, 12, 36, 228, DateTimeKind.Utc).AddTicks(2423),
                            Name = "TV"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2025, 4, 4, 12, 12, 36, 228, DateTimeKind.Utc).AddTicks(2424),
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Home & Kitchen",
                            CreatedAt = new DateTime(2025, 4, 4, 12, 12, 36, 228, DateTimeKind.Utc).AddTicks(2426),
                            Name = "Knife Set"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Sports",
                            CreatedAt = new DateTime(2025, 4, 4, 12, 12, 36, 228, DateTimeKind.Utc).AddTicks(2427),
                            Name = "Basketball"
                        });
                });

            modelBuilder.Entity("StoreVisitTracker.Domain.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 4, 12, 12, 36, 228, DateTimeKind.Utc).AddTicks(2378),
                            Location = "City A",
                            Name = "Store A"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 4, 12, 12, 36, 228, DateTimeKind.Utc).AddTicks(2380),
                            Location = "City B",
                            Name = "Store B"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 4, 4, 12, 12, 36, 228, DateTimeKind.Utc).AddTicks(2381),
                            Location = "City C",
                            Name = "Store C"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 4, 4, 12, 12, 36, 228, DateTimeKind.Utc).AddTicks(2383),
                            Location = "City D",
                            Name = "Store D"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 4, 4, 12, 12, 36, 228, DateTimeKind.Utc).AddTicks(2385),
                            Location = "City E",
                            Name = "Store E"
                        });
                });

            modelBuilder.Entity("StoreVisitTracker.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Role = "Admin",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = 2,
                            Role = "Admin",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = 3,
                            Role = "Standard",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 4,
                            Role = "Standard",
                            Username = "user2"
                        },
                        new
                        {
                            Id = 5,
                            Role = "Standard",
                            Username = "user3"
                        });
                });

            modelBuilder.Entity("StoreVisitTracker.Domain.Entities.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("StoreVisitTracker.Domain.Entities.Photo", b =>
                {
                    b.HasOne("StoreVisitTracker.Domain.Entities.Product", "Product")
                        .WithMany("Photos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreVisitTracker.Domain.Entities.Visit", "Visit")
                        .WithMany("Photos")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("StoreVisitTracker.Domain.Entities.Visit", b =>
                {
                    b.HasOne("StoreVisitTracker.Domain.Entities.Store", "Store")
                        .WithMany("Visits")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreVisitTracker.Domain.Entities.User", "User")
                        .WithMany("Visits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoreVisitTracker.Domain.Entities.Product", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("StoreVisitTracker.Domain.Entities.Store", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("StoreVisitTracker.Domain.Entities.User", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("StoreVisitTracker.Domain.Entities.Visit", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
